(function exposeCet4CoreDictionary() {
  const rawEntries = [
    "ability|能力|Practice improves your ability to communicate.",
    "absent|缺席|He was absent from the meeting.",
    "accept|接受|I accept your suggestion.",
    "accident|事故|The accident changed the traffic plan.",
    "account|账户|Please check your account settings.",
    "achieve|实现|We can achieve the goal together.",
    "active|积极的|She is active in class discussions.",
    "adapt|适应|We need to adapt to the new system.",
    "address|处理|The team will address the problem today.",
    "advance|进步|Technology continues to advance quickly.",
    "advantage|优势|This method has a clear advantage.",
    "advertise|宣传|The company will advertise the new product.",
    "affect|影响|Sleep can affect your memory.",
    "afford|负担得起|I cannot afford a new laptop right now.",
    "agriculture|农业|Agriculture is important to the economy.",
    "allow|允许|The app allows users to save words.",
    "amount|数量|A large amount of data was collected.",
    "ancient|古代的|This city has many ancient buildings.",
    "announce|宣布|They will announce the result tomorrow.",
    "anxious|焦虑的|Many students feel anxious before exams.",
    "appear|出现|A warning message appeared on the screen.",
    "apply|申请|You can apply for the program online.",
    "appreciate|感激|I appreciate your help.",
    "argue|争论|They often argue about small details.",
    "arrange|安排|Please arrange a meeting for Friday.",
    "article|文章|This article explains the problem clearly.",
    "assume|假设|Do not assume the user knows everything.",
    "attitude|态度|A positive attitude helps learning.",
    "audience|观众|The speaker knows his audience well.",
    "average|平均的|The average score increased this year.",
    "avoid|避免|Try to avoid unnecessary mistakes.",
    "balance|平衡|We need a balance between speed and quality.",
    "basic|基本的|This is a basic rule of grammar.",
    "behavior|行为|User behavior gives useful feedback.",
    "belief|信念|Her belief gives her strength.",
    "benefit|好处|Daily practice has many benefits.",
    "borrow|借入|Can I borrow your dictionary?",
    "brief|简短的|Give me a brief summary.",
    "budget|预算|The project has a limited budget.",
    "capacity|能力|The room has a capacity of fifty people.",
    "career|职业|He wants to build a career in design.",
    "cause|导致|Stress can cause health problems.",
    "certain|确定的|I am certain that this answer is correct.",
    "challenge|挑战|Learning a language is a real challenge.",
    "chance|机会|This is a good chance to improve.",
    "character|性格|Her character is calm and patient.",
    "charge|收费|The service does not charge extra fees.",
    "choice|选择|You have another choice.",
    "citizen|公民|Every citizen has responsibilities.",
    "climate|气候|The climate is changing around the world.",
    "combine|结合|We can combine the two ideas.",
    "comfortable|舒服的|This chair is comfortable.",
    "common|常见的|This is a common mistake.",
    "communicate|交流|It is important to communicate clearly.",
    "community|社区|The local community supports the project.",
    "compare|比较|Compare the two examples carefully.",
    "compete|竞争|Small companies compete with big brands.",
    "complain|抱怨|Users complain when the app is slow.",
    "complex|复杂的|The problem is more complex than it looks.",
    "concern|担心|Privacy is a major concern.",
    "condition|条件|The result depends on the condition.",
    "confident|自信的|She feels confident about the interview.",
    "connect|连接|This cable can connect the two devices.",
    "consequence|后果|Every decision has consequences.",
    "consider|考虑|Please consider this option.",
    "consist|由组成|The course consists of ten lessons.",
    "contact|联系|Contact support if you need help.",
    "contain|包含|The file contains important information.",
    "content|内容|The website has useful content.",
    "continue|继续|We will continue the discussion tomorrow.",
    "contribute|贡献|Everyone can contribute to the project.",
    "control|控制|Users should control their own data.",
    "convenient|方便的|Online payment is convenient.",
    "correct|正确的|Choose the correct answer.",
    "create|创造|The tool helps users create better sentences.",
    "culture|文化|Language is part of culture.",
    "curious|好奇的|Curious students learn faster.",
    "damage|损害|The storm caused serious damage.",
    "decision|决定|This is an important decision.",
    "decrease|减少|The cost may decrease next year.",
    "decline|下降|Sales began to decline in March.",
    "define|定义|Can you define this word?",
    "degree|程度|The problem changed to some degree.",
    "deliver|交付|The team will deliver the product soon.",
    "demand|需求|There is strong demand for the service.",
    "depend|依靠|Children depend on their parents.",
    "describe|描述|Describe the picture in English.",
    "design|设计|Good design makes the app easier to use.",
    "determine|决定|Your habits determine your progress.",
    "develop|发展|We need to develop better study habits.",
    "difference|差异|There is a big difference between them.",
    "difficult|困难的|The task is difficult but useful.",
    "direct|直接的|Please give me a direct answer.",
    "direction|方向|The project needs a clear direction.",
    "discover|发现|Scientists discovered a new method.",
    "discuss|讨论|Let's discuss the plan.",
    "distance|距离|The distance between the cities is short.",
    "economy|经济|The economy is growing slowly.",
    "education|教育|Education changes people's lives.",
    "effect|影响|The new rule has a clear effect.",
    "efficient|高效的|This tool makes learning more efficient.",
    "electronic|电子的|Electronic books are easy to carry.",
    "encourage|鼓励|Teachers encourage students to speak.",
    "energy|精力|He has a lot of energy in the morning.",
    "environment|环境|We should protect the environment.",
    "equipment|设备|The lab has modern equipment.",
    "establish|建立|They established a new company.",
    "event|事件|The event attracted many visitors.",
    "evidence|证据|We need more evidence.",
    "exact|准确的|Tell me the exact time.",
    "excellent|优秀的|She did an excellent job.",
    "exchange|交换|They exchange ideas every week.",
    "experience|经验|Experience helps you make better decisions.",
    "expert|专家|Ask an expert for advice.",
    "explain|解释|Can you explain this sentence?",
    "explore|探索|We will explore a new solution.",
    "express|表达|It is hard to express this idea.",
    "failure|失败|Failure can teach useful lessons.",
    "familiar|熟悉的|This word looks familiar.",
    "feature|特点|The app has a useful feature.",
    "field|领域|She works in the medical field.",
    "figure|数字|The figure shows a clear trend.",
    "final|最终的|This is the final version.",
    "finance|金融|Finance is important for business.",
    "flexible|灵活的|The schedule is flexible.",
    "focus|专注|Focus on one task at a time.",
    "foreign|外国的|Learning a foreign language takes time.",
    "former|以前的|The former manager left last year.",
    "freedom|自由|The internet gives people more freedom.",
    "frequent|频繁的|Frequent practice improves memory.",
    "function|功能|This function saves time.",
    "general|一般的|This is a general rule.",
    "generation|一代人|The younger generation uses phones often.",
    "global|全球的|Climate change is a global issue.",
    "goal|目标|Set a clear goal before you start.",
    "government|政府|The government announced a new policy.",
    "graduate|毕业|Many students graduate in June.",
    "habit|习惯|Reading is a good habit.",
    "handle|处理|Can you handle this task?",
    "harmful|有害的|Smoking is harmful to health.",
    "health|健康|Health is more important than money.",
    "honest|诚实的|Be honest about your mistakes.",
    "identify|识别|The system can identify common errors.",
    "imagine|想象|Imagine a better way to learn.",
    "immediate|立即的|The change had an immediate effect.",
    "improve|改善|Practice can improve your writing.",
    "include|包括|The report should include examples.",
    "income|收入|His income increased this year.",
    "increase|增加|The number of users will increase.",
    "independent|独立的|She is an independent learner.",
    "individual|个人|Each individual has different needs.",
    "industry|行业|The software industry changes quickly.",
    "influence|影响|Friends can influence your choices.",
    "information|信息|The page contains useful information.",
    "insist|坚持|He insists on doing the work himself.",
    "instead|代替|Use this method instead.",
    "intelligent|聪明的|She is an intelligent student.",
    "international|国际的|This is an international conference.",
    "interview|面试|The interview lasted thirty minutes.",
    "introduce|介绍|Let me introduce the new feature.",
    "issue|问题|We need to solve this issue.",
    "knowledge|知识|Knowledge grows through practice.",
    "labor|劳动|Manual labor can be difficult.",
    "language|语言|Language learning needs patience.",
    "legal|法律的|The company needs legal advice.",
    "local|当地的|Local people know the area well.",
    "major|主要的|This is a major change.",
    "manage|管理|It is hard to manage time well.",
    "material|材料|The material is strong and light.",
    "measure|衡量|We need to measure the result.",
    "method|方法|This method is simple and useful.",
    "modern|现代的|Modern technology changes education.",
    "natural|自然的|This sentence sounds natural.",
    "necessary|必要的|Sleep is necessary for health.",
    "notice|注意到|Did you notice the difference?",
    "object|物体|The object is made of metal.",
    "obvious|明显的|The answer is obvious.",
    "official|官方的|Check the official website.",
    "opportunity|机会|This is a great opportunity.",
    "ordinary|普通的|It was an ordinary day.",
    "organize|组织|We need to organize the files.",
    "participate|参加|Students should participate in class.",
    "particular|特别的|I like this particular example.",
    "patient|有耐心的|Be patient with yourself.",
    "perform|表现|She performed well in the test.",
    "period|时期|This period was full of change.",
    "personal|个人的|This is my personal opinion.",
    "persuade|说服|He tried to persuade me to stay.",
    "physical|身体的|Physical exercise is good for health.",
    "policy|政策|The company changed its policy.",
    "population|人口|The population of the city is growing.",
    "position|位置|Put the button in a better position.",
    "positive|积极的|Positive feedback helps learners.",
    "possible|可能的|It is possible to finish today.",
    "practical|实际的|This is a practical solution.",
    "prefer|更喜欢|I prefer simple examples.",
    "prepare|准备|Prepare your notes before class.",
    "pressure|压力|Students often feel pressure before exams.",
    "prevent|防止|Good habits prevent many problems.",
    "previous|以前的|Read the previous paragraph again.",
    "principle|原则|This principle is easy to understand.",
    "private|私人的|Keep private information safe.",
    "process|过程|Learning is a long process.",
    "produce|生产|The factory produces phones.",
    "professional|专业的|She gave a professional answer.",
    "progress|进步|You made real progress this week.",
    "protect|保护|Protect your personal data.",
    "provide|提供|The website provides useful tools.",
    "public|公共的|Public transport is convenient.",
    "purchase|购买|You can purchase the book online.",
    "purpose|目的|What is the purpose of this task?",
    "quality|质量|The quality of the product improved.",
    "range|范围|The app supports a wide range of words.",
    "react|反应|How did users react to the change?",
    "realize|意识到|I realized my mistake.",
    "receive|收到|Did you receive my message?",
    "recent|最近的|Recent news changed the plan.",
    "reduce|减少|We should reduce waste.",
    "reflect|反映|The data reflects user behavior.",
    "refuse|拒绝|He refused the offer.",
    "regular|定期的|Regular practice is important.",
    "relationship|关系|Trust improves the relationship.",
    "relative|相关的|The topic is relative to our work.",
    "release|发布|They will release the app next week.",
    "remain|保持|Please remain calm.",
    "remind|提醒|This note will remind you.",
    "remote|远程的|Remote work is common now.",
    "report|报告|Write a short report.",
    "require|需要|This task requires attention.",
    "research|研究|Research helps us understand the problem.",
    "resource|资源|Time is a valuable resource.",
    "respect|尊重|We should respect different opinions.",
    "responsible|负责的|She is responsible for the project.",
    "result|结果|The result was better than expected.",
    "risk|风险|There is a risk of failure.",
    "safety|安全|Safety comes first.",
    "schedule|日程|The schedule is full today.",
    "scientific|科学的|This is a scientific method.",
    "select|选择|Select the best answer.",
    "separate|分开|Keep these files separate.",
    "serious|严重的|This is a serious problem.",
    "service|服务|The service is fast and reliable.",
    "signal|信号|The signal is weak here.",
    "similar|相似的|The two words are similar.",
    "situation|情况|The situation changed quickly.",
    "social|社会的|Social skills are useful.",
    "society|社会|Technology changes society.",
    "solution|解决方案|We found a better solution.",
    "source|来源|Check the source of the information.",
    "special|特别的|This is a special case.",
    "specific|具体的|Give me a specific example.",
    "standard|标准|The product meets the standard.",
    "structure|结构|The sentence structure is simple.",
    "succeed|成功|You can succeed with practice.",
    "suggest|建议|I suggest a different method.",
    "suitable|合适的|This course is suitable for beginners.",
    "supply|供应|The supply of water is limited.",
    "support|支持|The team will support your decision.",
    "surface|表面|The surface is smooth.",
    "suppose|假设|Suppose we start tomorrow.",
    "task|任务|Finish one task at a time.",
    "technology|技术|Technology makes learning easier.",
    "traffic|交通|Traffic is heavy today.",
    "tradition|传统|This tradition has a long history.",
    "transport|运输|Public transport saves money.",
    "valuable|有价值的|Your feedback is valuable.",
    "value|价值|This tool has real value.",
    "variety|多样性|The course offers a variety of examples.",
    "various|各种各样的|Various methods can solve the problem.",
    "volunteer|志愿者|She works as a volunteer.",
    "waste|浪费|Do not waste your time.",
    "wealth|财富|Health is greater than wealth.",
    "willing|愿意的|I am willing to try again."
  ];

  window.AEL_CET4_CORE = rawEntries.map((row) => {
    const [en, zh, example, phonetic = ""] = row.split("|");
    return {
      id: `cet4-${slug(en)}`,
      zh,
      en,
      phonetic,
      zhExplanation: `${zh}；大学英语四级核心常用词。`,
      enExplanation: `CET-4 core word: ${zh}`,
      example,
      difficulty: "CET4",
      kind: "builtin"
    };
  });

  function slug(value) {
    return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  }
})();
